# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Metropolis sampler using Rcpp 
#' @description A Metropolis sampler using Rcpp to generate random variables from a standard Cauchy distribution
#' @param sigma the parameter of proposal distribution Normal
#' @param x0 the initial value of sample
#' @param N the number of samples
#' @return a random sample of size N and the number of reject 
#' @examples
#' \dontrun{
#' rwC <- rwcc(0.5,25,2000)
#' print(rwC$x)
#' print(rwC$k)
#' }
#' @export
rwcc <- function(sigma, x0, N) {
    .Call('_StatComp20066_rwcc', PACKAGE = 'StatComp20066', sigma, x0, N)
}

